
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      Microsoft (R) Visual C++ Express Edition Version 9.0.21022.8.
      Copyright (C) Microsoft Corp 2007. All rights reserved.
      1>------ Build started: Project: CompilerIdC, Configuration: Debug Win32 ------
      1>Compiling...
      1>CMakeCCompilerId.c
      1>Linking...
      1>Embedding manifest...
      1>Performing Post-Build Event...
      1>CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\cl.exe
      1>Build log was saved at "file://c:\\Users\\eduar\\Documents\\Visual Studio 2008\\Projects\\Estudos\\Praticas\\CMakeFiles\\3.26.4\\CompilerIdC\\Debug\\BuildLog.htm"
      1>CompilerIdC - 0 error(s), 0 warning(s)
      ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      Microsoft (R) Visual C++ Express Edition Version 9.0.21022.8.
      Copyright (C) Microsoft Corp 2007. All rights reserved.
      1>------ Build started: Project: CompilerIdCXX, Configuration: Debug Win32 ------
      1>Compiling...
      1>CMakeCXXCompilerId.cpp
      1>Linking...
      1>Embedding manifest...
      1>Performing Post-Build Event...
      1>CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\cl.exe
      1>Build log was saved at "file://c:\\Users\\eduar\\Documents\\Visual Studio 2008\\Projects\\Estudos\\Praticas\\CMakeFiles\\3.26.4\\CompilerIdCXX\\Debug\\BuildLog.htm"
      1>CompilerIdCXX - 0 error(s), 0 warning(s)
      ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-wq5s9m"
      binary: "C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-wq5s9m"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-wq5s9m
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/VCExpress.exe CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_7cb5a && 
        Microsoft (R) Visual C++ Express Edition Version 9.0.21022.8.
        Copyright (C) Microsoft Corp 2007. All rights reserved.
        1>------ Build started: Project: cmTC_7cb5a, Configuration: Debug Win32 ------
        1>Compiling...
        1>Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.21022.08 for 80x86
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>cl /Od /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\\"Debug\\"" /D "_MBCS" /FD /RTC1 /MDd /Fo"cmTC_7cb5a.dir\\Debug\\\\" /Fd"cmTC_7cb5a.dir\\Debug\\vc90.pdb" /W3 /c /Zi /TC "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        1>CMakeCCompilerABI.c
        1>Compiling manifest to resources...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Linking...
        1>Embedding manifest...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Build log was saved at "file://c:\\Users\\eduar\\Documents\\Visual Studio 2008\\Projects\\Estudos\\Praticas\\CMakeFiles\\CMakeScratch\\TryCompile-wq5s9m\\cmTC_7cb5a.dir\\Debug\\BuildLog.htm"
        1>cmTC_7cb5a - 0 error(s), 0 warning(s)
        ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-spv9eb"
      binary: "C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-spv9eb"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/eduar/Documents/Visual Studio 2008/Projects/Estudos/Praticas/CMakeFiles/CMakeScratch/TryCompile-spv9eb
        
        Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/VCExpress.exe CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_a7d34 && 
        Microsoft (R) Visual C++ Express Edition Version 9.0.21022.8.
        Copyright (C) Microsoft Corp 2007. All rights reserved.
        1>------ Build started: Project: cmTC_a7d34, Configuration: Debug Win32 ------
        1>Compiling...
        1>Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.21022.08 for 80x86
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>cl /Od /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\\"Debug\\"" /D "_MBCS" /FD /EHsc /RTC1 /MDd /Fo"cmTC_a7d34.dir\\Debug\\\\" /Fd"cmTC_a7d34.dir\\Debug\\vc90.pdb" /W3 /c /Zi /TP "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        1>CMakeCXXCompilerABI.cpp
        1>Compiling manifest to resources...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Linking...
        1>Embedding manifest...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Build log was saved at "file://c:\\Users\\eduar\\Documents\\Visual Studio 2008\\Projects\\Estudos\\Praticas\\CMakeFiles\\CMakeScratch\\TryCompile-spv9eb\\cmTC_a7d34.dir\\Debug\\BuildLog.htm"
        1>cmTC_a7d34 - 0 error(s), 0 warning(s)
        ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        
      exitCode: 0
...
